/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ..\assets\models\plane.gltf 
Author: MasterOfGaming020 (https://sketchfab.com/MasterOfGaming020)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/paper-plane-6e9201cd4b614d879741ea79524c57c6
Title: Paper Plane
*/

import React from 'react'
import { useGLTF,useTexture } from '@react-three/drei'
import { DissolveMaterial } from './DissolveMaterial'
import * as THREE from "three";
// import planeTexture from '../assets/images/plane_texture.jpeg';


export default function Model(props) {
  // let tex = useTexture(planeTexture)
  const { nodes, materials } = useGLTF('/models/plane.gltf')
  const planeMaterial = new THREE.MeshStandardMaterial({color:'white'})
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={planeMaterial} rotation={[Math.PI / 2, 0, 0]}>
        <DissolveMaterial
          baseMaterial={planeMaterial}
          visible={props.dissolveVisible}
          onFadeOut={props.onFadeOut}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload('/plane.gltf')
